"""Add subscription fields to User

Revision ID: 77e07affa049
Revises: 0bea81e82bea
Create Date: 2025-06-20 11:40:45.299574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e07affa049'
down_revision: Union[str, None] = '0bea81e82bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'image_url')
    op.add_column('users', sa.Column('is_subscribed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('subscription_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_expiry')
    op.drop_column('users', 'is_subscribed')
    op.add_column('news', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
