"""re-add image_url column

Revision ID: 8b7afa47e65d
Revises: 018a9965ac78
Create Date: 2025-06-27 00:35:49.380996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7afa47e65d'
down_revision: Union[str, None] = '018a9965ac78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'image_url')
    # ### end Alembic commands ###
