"""add like_count and comment_count

Revision ID: e07b396af9a1
Revises: ff0a35ceaaba
Create Date: 2025-07-05 09:46:25.337126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e07b396af9a1'
down_revision: Union[str, None] = 'ff0a35ceaaba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revenue_date', table_name='revenue')
    op.drop_table('revenue')
    op.drop_table('subscription_plans')
    op.drop_column('users', 'is_subscribed')
    op.drop_column('users', 'subscription_expiry')
    op.add_column('videos', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('comment_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'comment_count')
    op.drop_column('videos', 'like_count')
    op.add_column('users', sa.Column('subscription_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_subscribed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subscription_plans_pkey')
    )
    op.create_table('revenue',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='revenue_pkey')
    )
    op.create_index('ix_revenue_date', 'revenue', ['date'], unique=False)
    # ### end Alembic commands ###
