"""add created_at to categories

Revision ID: ff0a35ceaaba
Revises: 8b7afa47e65d
Create Date: 2025-06-30 00:12:45.429777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff0a35ceaaba'
down_revision: Union[str, None] = '8b7afa47e65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
